name: 'Fenwick & West Branding'
favicon: null
layout_spectrum: 0.00565
typography_spectrum: 0.63204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c3d600'
    - '#62cbe1'
    - '#243746'
    - '#fd4513'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
